import type { Project } from "./project.types";

export const projects: Project[] = [
  {
    slug: "sagi",
    name: "Sagi.store",
    category: "E-commerce",
    year: "",
    format: "Sklep internetowy",
    role: "Frontend development",
    url: "https://sagi.store/",
    overview:
      "Sagi.store to sklep z odzieżą i akcesoriami twórcy Sagi. Kolekcja jest w centrum uwagi: duże zdjęcia, wyraźne nazwy i oszczędna oprawa pozwalają szybko przejść od przeglądania produktów do wyboru konkretnego modelu.",
    challenge:
      "Połączyć charakter marki z prostym interfejsem sklepu. Użytkownik powinien łatwo odnaleźć kolekcję, sprawdzić cenę i dostępne rozmiary, a następnie przejść do koszyka.",
    solution:
      "Jasne tło i czarno-biała typografia zostawiają przestrzeń produktom. Kategorie porządkują ofertę, a karta produktu skupia zdjęcie, wybór rozmiaru i najważniejsze informacje w jednym widoku. Frontend powstał w HTML i CSS.",
    scope: [
      "Frontend w HTML i CSS",
      "Widoki kolekcji i produktów",
      "Prezentacja wariantów i informacji o produkcie",
      "Responsywny układ strony",
    ],
    technologies: ["html", "css"],
    tagline: "Kolekcja na pierwszym planie.",
    description:
      "Frontend sklepu Sagi.store w HTML i CSS. Minimalistyczna oprawa, duże zdjęcia i czytelna prezentacja kolekcji oraz produktów.",
    image: "/images/sagi-cover-v4.webp",
    width: 1440,
    height: 960,
    alt: "Kolekcja odzieży i akcesoriów na stronie sklepu Sagi.store",
    tags: ["HTML / CSS", "E-commerce"],
    background: "#f8f8f8",
    gallery: [
      {
        src: "/images/sagi-cover-v4.webp",
        alt: "Kolekcja odzieży i akcesoriów na stronie sklepu Sagi.store",
        caption: "Kolekcja — produkt w centrum uwagi",
        width: 1440,
        height: 960,
      },
      {
        src: "/images/sagi-product.webp",
        alt: "Karta brązowej bluzy w Sagi.store: zdjęcie, cena, rozmiary i informacje o produkcie",
        caption: "Karta produktu — od zdjęcia do wyboru rozmiaru",
        width: 1280,
        height: 720,
      },
    ],
  },
  {
    slug: "vetly",
    name: "Vetly",
    category: "Platforma usługowa",
    year: "",
    format: "Aplikacja internetowa",
    role: "UI/UX + frontend development",
    url: "https://vetly.pl/",
    overviewTitle: "Znajdź. Porównaj. Wybierz.",
    overview:
      "Vetly pomaga właścicielom zwierząt znaleźć weterynarza lub groomera w swojej okolicy. Wyszukiwarka łączy listę placówek z mapą, a profile zbierają oceny, godziny otwarcia i dane kontaktowe. Odpowiadałem za projekt UI/UX oraz wdrożenie frontendu w React i Inertia.js.",
    challenge:
      "Uporządkować wiele informacji tak, żeby wybór placówki był prosty. Lokalizacja, rodzaj usług, oceny i godziny otwarcia powinny pomagać w podjęciu decyzji, bez konieczności przeskakiwania między wieloma stronami.",
    solution:
      "Ścieżka zaczyna się od wyboru miejscowości i typu specjalisty. Wyniki zestawiają najważniejsze informacje z mapą, a profil kliniki prowadzi do godzin otwarcia, lokalizacji i kontaktu. Spokojna zielona paleta oraz ilustracje zwierząt nadają interfejsowi przyjazny charakter. Frontend został wdrożony w React z Inertia.js.",
    scope: [
      "Projekt UI/UX i hierarchia informacji",
      "Frontend w React i Inertia.js",
      "Widoki wyszukiwania i filtrowania",
      "Profile placówek oraz prezentacja mapy",
      "Responsywny interfejs",
    ],
    technologies: ["react", "inertia"],
    tagline: "Właściwa opieka. Bliżej Ciebie.",
    description:
      "Projekt UI/UX i frontend Vetly w React oraz Inertia.js. Wyszukiwanie weterynarzy i groomerów, lista wyników z mapą oraz profile placówek.",
    image: "/images/vetly-home.webp",
    width: 1440,
    height: 960,
    alt: "Strona główna Vetly z wyszukiwarką specjalistów i kolorowymi ilustracjami zwierząt",
    tags: ["UI/UX", "React / Inertia.js"],
    background: "#f6f8f6",
    gallery: [
      {
        src: "/images/vetly-home.webp",
        alt: "Strona główna Vetly z wyszukiwarką specjalistów i ilustracjami zwierząt",
        caption: "Pierwszy krok — znajdź specjalistę w swojej okolicy",
        width: 1440,
        height: 960,
      },
      {
        src: "/images/vetly-search.webp",
        alt: "Lista klinik w Gdańsku z ocenami, godzinami otwarcia i mapą",
        caption: "Porównaj placówki — wyniki i mapa obok siebie",
        width: 1440,
        height: 960,
      },
      {
        src: "/images/vetly-profile.webp",
        alt: "Profil kliniki w Vetly z godzinami otwarcia, lokalizacją i szybkim kontaktem",
        caption: "Profil kliniki — najważniejsze informacje i kontakt",
        width: 1440,
        height: 960,
      },
    ],
  },
  {
    slug: "paymentic",
    name: "Paymentic",
    category: "Fintech",
    year: "",
    format: "Onboarding firm",
    role: "UI/UX + frontend development",
    url: "https://onb.paymentic.com/",
    overviewTitle: "Prosty początek. Jasny następny krok.",
    overview:
      "Paymentic umożliwia firmom rozpoczęcie rejestracji do przyjmowania płatności online. Ekran startowy wyjaśnia, co przygotować, a formularz zbiera dane osoby kontaktowej oraz numer NIP firmy. Odpowiadałem za projekt UI, wdrożenie frontendu w Next.js i podłączenie formularza do obsługi procesu rejestracji.",
    challenge:
      "Przedstawić wymagania związane z rejestracją w czytelny sposób i ułatwić pierwszy krok. Użytkownik powinien wiedzieć, jakie dane przygotować i czego spodziewać się przed rozpoczęciem procesu.",
    solution:
      "Układ dzieli ekran na komunikację marki i część zadaniową. Na początku krótka lista porządkuje wymagania, a w formularzu wyraźne etykiety, przykłady i informacje pomocnicze prowadzą przez dane kontaktowe oraz dane firmy. Niebieskie akcenty wskazują główne działania. Zaprojektowany interfejs wdrożyłem w Next.js i podłączyłem formularz do obsługi procesu rejestracji.",
    scope: [
      "Projekt UI i hierarchia informacji",
      "Frontend w Next.js",
      "Podłączenie formularza do procesu rejestracji",
      "Ekran przygotowania do rejestracji",
      "Interfejs formularza kontaktowego i danych firmy",
      "Responsywny układ widoków",
    ],
    technologies: ["nextjs"],
    tagline: "Pierwszy krok do płatności online.",
    description:
      "Projekt UI i frontend onboardingu Paymentic w Next.js, z podłączeniem formularza. Czytelne przygotowanie do rejestracji i formularz danych kontaktowych oraz danych firmy.",
    image: "/images/paymentic-home.webp",
    width: 1440,
    height: 960,
    alt: "Ekran startowy Paymentic z listą informacji potrzebnych przed rejestracją",
    tags: ["UI/UX", "Next.js"],
    background: "#f5f5fb",
    gallery: [
      {
        src: "/images/paymentic-home.webp",
        alt: "Ekran startowy Paymentic z informacjami o telefonie, stronie WWW i weryfikacji",
        caption: "Przed rejestracją — wymagania w jednym miejscu",
        width: 1440,
        height: 960,
      },
      {
        src: "/images/paymentic-form.webp",
        alt: "Formularz rejestracyjny Paymentic z polami danych kontaktowych, kraju i numeru NIP",
        caption: "Formularz — czytelne dane i wyraźny następny krok",
        width: 1440,
        height: 960,
      },
    ],
  },
  {
    slug: "jkmedacademy",
    name: "JK Med Academy",
    category: "Edukacja / Beauty",
    year: "",
    format: "Strona centrum szkoleniowego",
    role: "UI + frontend development",
    url: "https://jkmedacademy.pl/",
    overviewTitle: "Od oferty do kontaktu.",
    overview:
      "JK Med Academy to centrum szkoleń z kosmetologii i medycyny estetycznej. Strona prezentuje ofertę, programy kursów, terminy oraz zespół prowadzących. Odpowiadałem za projekt UI, frontend w Next.js i podłączenie formularzy.",
    challenge:
      "Połączyć elegancki charakter marki z czytelną prezentacją rozbudowanej oferty. Osoba zainteresowana szkoleniem powinna łatwo odnaleźć program, sprawdzić najważniejsze informacje i przejść do kontaktu.",
    solution:
      "Ciepła paleta, szeryfowe nagłówki i duże fotografie tworzą spokojną oprawę. Karty porządkują ofertę, a podstrony szkoleń prowadzą od krótkiego wprowadzenia do programu i terminów. Zaprojektowany interfejs wdrożyłem w Next.js oraz podłączyłem formularze.",
    scope: [
      "Projekt UI i hierarchia informacji",
      "Frontend w Next.js",
      "Widoki oferty i szczegółów szkoleń",
      "Prezentacja terminów, zespołu i kontaktu",
      "Podłączenie formularzy",
      "Responsywny układ strony",
    ],
    technologies: ["nextjs"],
    tagline: "Wiedza w dobrej formie.",
    description:
      "Projekt UI i frontend JK Med Academy w Next.js, z podłączeniem formularzy. Oferta szkoleń, szczegółowe programy kursów i elegancka oprawa strony.",
    image: "/images/jkmed-home.webp",
    width: 1440,
    height: 960,
    alt: "Strona główna JK Med Academy z szeryfowym nagłówkiem i portretem trenerki w ciepłej beżowej oprawie",
    tags: ["UI design", "Next.js"],
    background: "#f7f5f1",
    gallery: [
      {
        src: "/images/jkmed-home.webp",
        alt: "Strona główna JK Med Academy z nagłówkiem akademii i portretem trenerki",
        caption: "Pierwsze wrażenie — typografia, fotografia i ciepła paleta",
        width: 1440,
        height: 960,
      },
      {
        src: "/images/jkmed-offer.webp",
        alt: "Katalog szkoleń JK Med Academy z siatką kart kursów",
        caption: "Oferta — programy uporządkowane w kartach",
        width: 1440,
        height: 960,
      },
      {
        src: "/images/jkmed-course.webp",
        alt: "Podstrona szkolenia z oczyszczania wodorowego z opisem i programem",
        caption: "Szczegóły szkolenia — od wprowadzenia do programu",
        width: 1440,
        height: 960,
      },
    ],
  },
  {
    slug: "fizjomiara",
    name: "FizjoMiara",
    category: "Aplikacja / Healthtech",
    year: "",
    format: "Aplikacja webowa / PWA",
    role: "Projekt własny",
    url: "https://fizjomiara.vercel.app/",
    sourceUrl: "https://github.com/kamilklasa/fizjomiara",
    overviewTitle: "Pomiary bez chaosu.",
    overview:
      "FizjoMiara to aplikacja dla fizjoterapeutów, która porządkuje powtarzalne pomiary obwodów i długości kończyn. Łączy kartę pacjenta, szablony pomiarowe i historię sesji. Zamiast szukać wartości w kolejnych notatkach, można zestawić aktualny wynik z poprzednim i pierwszym pomiarem. Kod projektu jest dostępny na GitHubie.",
    challenge:
      "Zachować spójność pomiarów między sesjami i ułatwić odczytywanie zmian. Interfejs powinien jasno rozróżniać lewą i prawą stronę, pokazywać jednostki oraz pozwalać wrócić do wcześniejszych wyników bez przepisywania danych.",
    solution:
      "Szablony określają zestaw pomiarów, a uporządkowany formularz zapisuje wartości automatycznie. Zakończona sesja przechodzi w tryb odczytu, z osobnym trybem korekty. Tabela porównuje wyniki oraz oblicza różnice liczbowe i procentowe, a historia zbiera kolejne sesje w profilu pacjenta. React i TypeScript odpowiadają za interfejs, TanStack za nawigację i dane, a Supabase za logowanie i zapis w PostgreSQL.",
    scope: [
      "Karty pacjentów i historia sesji",
      "Szablony oraz formularze pomiarowe",
      "Autozapis i zatwierdzanie wyników",
      "Porównania sesji i wizualizacja zmian",
      "Logowanie i przechowywanie danych w Supabase",
      "Responsywny interfejs i PWA",
    ],
    technologies: [
      "react",
      "typescript",
      "tailwind",
      "tanstackRouter",
      "tanstack",
      "supabase",
      "postgresql",
      "valibot",
    ],
    tagline: "Od pomiaru do czytelnej historii.",
    description:
      "FizjoMiara — aplikacja webowa w React i TypeScript z Supabase. Karty pacjentów, pomiary, historia i porównania sesji. Kod projektu na GitHubie.",
    image: "/images/fizjomiara-comparison.webp",
    width: 1440,
    height: 960,
    alt: "Interfejs FizjoMiary z tabelą porównań sesji i fioletowymi akcentami",
    tags: ["React / TypeScript", "Supabase"],
    background: "#f7f6fa",
    gallery: [
      {
        src: "/images/fizjomiara-comparison.webp",
        alt: "Tabela porównująca pomiary z pierwszej, poprzedniej i aktualnej sesji na fikcyjnych danych",
        caption: "Porównanie sesji — różnice w jednym widoku",
        width: 1440,
        height: 960,
      },
      {
        src: "/images/fizjomiara-measurements.webp",
        alt: "Formularz pomiarów kończyn z wartościami lewej i prawej strony na fikcyjnych danych",
        caption: "Pomiary — czytelny podział na lewą i prawą stronę",
        width: 1440,
        height: 960,
      },
      {
        src: "/images/fizjomiara-patient.webp",
        alt: "Karta przykładowego pacjenta z podsumowaniem zmian i historią dwóch sesji",
        caption: "Karta pacjenta — wyniki i historia w jednym miejscu",
        width: 1440,
        height: 960,
      },
    ],
  },
  {
    slug: "hostero",
    name: "Hostero",
    category: "Hosting / Usługi",
    year: "",
    format: "Strona usługowa",
    role: "Frontend development",
    url: "https://hostero.pl/",
    overviewTitle: "Od oferty do wyboru serwera.",
    overview:
      "Hostero to serwis oferujący hosting serwerów gier i botów Discord. Strona prowadzi od prezentacji marki, przez katalog obsługiwanych gier, do porównania pakietów i ich parametrów. Mój zakres obejmował kodowanie frontendu w Next.js na podstawie dostarczonego projektu graficznego.",
    challenge:
      "Przełożyć rozbudowany projekt graficzny na działającą stronę, zachowując jego charakter i czytelność. Katalog gier, warianty oferty oraz parametry techniczne wymagają spójnego układu na komputerach i telefonach.",
    solution:
      "Frontend w Next.js łączy wyrazistą stronę główną z katalogiem usług i podstronami konkretnych gier. Karty pakietów zestawiają cenę oraz zasoby serwera, a przełączniki okresu i lokalizacji porządkują wybór wariantu. Duże grafiki, niebieskie akcenty i powtarzalne elementy interfejsu zachowują charakter dostarczonego projektu.",
    scope: [
      "Kodowanie frontendu w Next.js",
      "Wdrożenie dostarczonego projektu graficznego",
      "Strona główna i katalog usług",
      "Widoki oferty oraz prezentacja pakietów",
      "Responsywne układy i interakcje interfejsu",
    ],
    technologies: ["nextjs"],
    tagline: "Hosting w czytelnej formie.",
    description:
      "Frontend strony Hostero w Next.js na podstawie dostarczonego projektu graficznego. Katalog usług, oferta hostingu gier i prezentacja pakietów serwerów.",
    image: "/images/hostero-home.webp",
    width: 1436,
    height: 957,
    alt: "Strona główna Hostero z niebieskim akcentem, nagłówkiem i fotografią gracza w goglach VR",
    tags: ["Frontend", "Next.js"],
    background: "#f5f7fb",
    gallery: [
      {
        src: "/images/hostero-home.webp",
        alt: "Strona główna Hostero z prezentacją marki i fotografią gracza w goglach VR",
        caption: "Strona główna — wyrazista oprawa usług",
        width: 1436,
        height: 957,
      },
      {
        src: "/images/hostero-offer.webp",
        alt: "Katalog Hostero z kartami hostingu Minecraft, GTA 5, Valheim i innych gier",
        caption: "Katalog — od wyboru gry do konkretnej oferty",
        width: 1436,
        height: 957,
      },
      {
        src: "/images/hostero-minecraft.webp",
        alt: "Karty pakietów Minecraft z zasobami serwera, ceną i wyborem okresu oraz lokalizacji",
        caption: "Pakiety — parametry i warianty obok siebie",
        width: 1436,
        height: 957,
      },
    ],
  },
];
